/*1.- (3,5 ptos) Realiza un procedimiento que le pases 
un rango de notas, un IDE y un porcentaje de subida, 
te actualice su nota para ese examen en el 
rango indicada subiéndole el porcentaje indicado. 
Ej SubeNota 7, 8,  4, 10  subiría un 10% la nota para 
el examen con ide 4 si su calificación está entre 7 y 8.
Borra el procedimiento*/


/*2.- (1 ptos) Añádele control 
de errores para que deshaga los 
cambios si encuentra cualquier error.*/


/*3.- (3 ptos) Realiza una función que 
dadas una calificación y un ide te 
devuelva el nombre de pila del 
alumno que haya sacado esa nota. 
Si ha varios, el de mayor dni. Borra la función*/
/*4.- (2,5 ptos) Desactiva los disparadores activos. 
Crea un disparador que controle las notas de los 
exámenes están en los rangos normales (0-10). 
Borra el disparador*/