/*EJ1*/
select Pais,(Poblacion/Superficie) from Paises where (Poblacion/Superficie) > 100
/*EJ2*/
select Pais,Poblacion from Paises where (Poblacion/Superficie) > 100
ORDER BY Poblacion DESC
/*EJ3*/

/*EJ13*/
SELECT LENGUA,COUNT(PAIS) AS "N PAISES" FROM Paises GROUP BY Lengua
/*EJ14*/
SELECT CONTINENTE,COUNT (PAIS)AS "N PAISES" FROM Paises GROUP BY Continente
/*EJ15*/
SELECT CONTINENTE,COUNT (PAIS) FROM Paises WHERE Continente NOT LIKE 'Europa' AND CONTINENTE NOT LIKE 'ASIA' GROUP BY Continente
/*EJ16*/
SELECT RELIGION,Pais FROM Paises ORDER BY Religion
/*EJ17*/
SELECT RELIGION, COUNT(Pais)AS "N PAISES "FROM Paises GROUP BY RELIGION
/*EJ18*/
SELECT CONTINENTE, SUM(Superficie) AS "SUPERFICIE" FROM Paises GROUP BY Continente
/*EJ19*/
SELECT CONTINENTE, AVG(Superficie) AS "SUPERFICIE" FROM Paises GROUP BY Continente
/*EJ20*/
SELECT CONTINENTE,COUNT (PAIS) AS PAISES FROM Paises WHERE Superficie>20000 GROUP BY Continente
/*EJ21*/
SELECT CONTINENTE,SUM(POBLACION) AS POBLACION FROM Paises WHERE Superficie>100000 GROUP BY Continente
/*EJ22*/
SELECT CONTINENTE,COUNT(PAIS) FROM Paises WHERE Superficie<1000 GROUP BY Continente HAVING COUNT (PAIS)>5
/*EJ23*/
SELECT CONTINENTE,RELIGION,COUNT (Pais)AS "N PAISES" FROM Paises GROUP BY Continente,RELIGION