/*EJ1*/
SELECT DISTINCT ALUMNOS.DNIA,ALUMNOS.nombre,ALUMNOS.apellidos FROM ALUMNOS
WHERE ALUMNOS.nombre='MANUEL'
/*EJ2*/
SELECT PADRES.DNIP,PADRES.nombre,PADRES.apellidos FROM PADRES
WHERE PADRES.apellidos LIKE '%CASTRO'
/*EJ3*/
SELECT ALUMNOS.nombre AS Nombre,ALUMNOS.apellidos AS Apellidos,ASIGNATURAS.nombre AS Asignatura FROM ALUMNOS LEFT JOIN ASIGNATURAS
ON ASIGNATURAS.IDA=ALUMNOS.DNIA
/*EJ4*/
SELECT ALUMNOS.nombre AS Nombre_alumno,ALUMNOS.apellidos AS Apellido_alumno,PADRES.nombre AS Nombre_padre,PADRES.apellidos AS Apellidos_padre FROM ALUMNOS LEFT JOIN PADRES
ON ALUMNOS.DNIA=PADRES.DNIP
/*EJ5*/
SELECT EXAMENES.* FROM EXAMENES LEFT JOIN ASIGNATURAS
ON ASIGNATURAS.IDA=EXAMENES.IDA
WHERE EXAMENES.fecha LIKE '2004%' AND EXAMENES.observaciones='MATEMATICAS'
/*EJ6*/
SELECT ALUMNOS.nombre,ALUMNOS.apellidos,NOTAS.calificacion FROM ALUMNOS LEFT JOIN NOTAS
ON NOTAS.DNIA=ALUMNOS.DNIA
WHERE calificacion>=(select max(NOTAS.calificacion) from ALUMNOS left join NOTAS
on ALUMNOS.DNIA=NOTAS.DNIA
where ALUMNOS.nombre='MANUEL' AND ALUMNOS.apellidos='ESPEJO MARTINEZ')
/*EJ7*/
SELECT ALUMNOS.nombre,ALUMNOS.apellidos,NOTAS.calificacion FROM ALUMNOS LEFT JOIN NOTAS
ON NOTAS.DNIA=ALUMNOS.DNIA
WHERE calificacion>=(select max(NOTAS.calificacion) from ALUMNOS left join NOTAS
on ALUMNOS.DNIA=NOTAS.DNIA
where ALUMNOS.nombre='MANUEL' AND ALUMNOS.apellidos='ESPEJO MARTINEZ')
/*EJ8*/
SELECT ASIGNATURAS.nombre,AVG(NOTAS.CALIFICACION) AS MEDIA FROM NOTAS LEFT JOIN ASIGNATURAS
ON NOTAS.IDE=ASIGNATURAS.IDA WHERE ASIGNATURAS.nombre='INFORMATICA'
GROUP BY ASIGNATURAS.nombre
/*EJ9*/
SELECT ASIGNATURAS.nombre,AVG(NOTAS.CALIFICACION) FROM NOTAS LEFT JOIN ASIGNATURAS
ON NOTAS.IDE=ASIGNATURAS.IDA
GROUP BY ASIGNATURAS.nombre
/*EJ10*/
SELECT ASIGNATURAS.nombre,COUNT(DISTINCT EXAMENES.IDE)AS NUMERO_DE_EXAMENES FROM EXAMENES LEFT JOIN ASIGNATURAS
ON EXAMENES.IDA=ASIGNATURAS.IDA
GROUP BY ASIGNATURAS.nombre
/*EJ11*/
SELECT ASIGNATURAS.nombre,COUNT(DISTINCT EXAMENES.IDE)AS NUMERO_DE_ASIGNATURAS FROM EXAMENES LEFT JOIN ASIGNATURAS
ON EXAMENES.IDA=ASIGNATURAS.IDA
GROUP BY ASIGNATURAS.nombre
/*EJ12*/
SELECT ALUMNOS.nombre,ALUMNOS.apellidos,AVG(NOTAS.calificacion)AS NOTA_MEDIA FROM ALUMNOS LEFT JOIN NOTAS
ON NOTAS.DNIA=ALUMNOS.DNIA
GROUP BY ALUMNOS.nombre,ALUMNOS.apellidos
/*EJ13*/
SELECT ALUMNOS.DNIA FROM ALUMNOS LEFT JOIN NOTAS
ON NOTAS.DNIA=ALUMNOS.DNIA
WHERE NOTAS.calificacion>=(SELECT AVG(NOTAS.calificacion) FROM NOTAS)
GROUP BY ALUMNOS.DNIA